TebLocalPlannerROS:

  odom_topic: /odom
  map_frame: map

  # 로봇 제한(차등구동 예시)
  max_vel_x: 0.6
  max_vel_x_backwards: 0.5
  max_vel_theta: 1.6
  acc_lim_x: 1.5
  acc_lim_theta: 3.0

  # 궤적 시간 해상도
  dt_ref: 0.2
  dt_hysteresis: 0.05
  global_plan_overwrite_orientation: false
  max_global_plan_lookahead_dist: 1.5

  # 목표 허용오차
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.10
  free_goal_vel: false

   # === 장애물/여유 (TEB 내부 소프트 여유) ===
  include_costmap_obstacles: false
  min_obstacle_dist: 0.001        
  inflation_dist: 0.2         # min보다 커야 부드러운 유도 효과↑
  obstacle_cost_exponent: 20.0    # 가까울수록 비용 급격히↑
  obstacle_poses_affected: 20     # 15 → 8 (과도한 상호작용 완화)
  costmap_obstacles_behind_robot_dist: 0.01

  # === 최적화 가중치 (동결/지그재그 방지) ===
  weight_kinematics_nh: 1200   # 1000 → 500 (회전·재배치 유연성↑)
  weight_obstacle: 5.0          # 50 → 40 (벽에 과도하게 눌리지 않게)
  weight_optimaltime: 5.0       # 1 → 25 
  weight_viapoint: 10.0          # 아래 viapoints를 쓸 경우

  # === 전역 플랜 추종(좁은 통로에서 중심선 붙잡기) ===
  via_points_ordered: true
  global_plan_viapoint_sep: 0.2   # 0.3~0.5 권장
  

  # 풋프린트 모델 (TEB 내부 충돌체크)
  footprint_model:
    type: "polygon"               # point, circle, line, two_circles, polygon
    vertices: [[0.30, 0.30], [0.30, -0.30], [-0.30, -0.30], [-0.30, 0.30]]
    # is_footprint_dynamic: false  # 필요시 동적 업데이트

  # === 초기화/리커버리 ===
  allow_init_with_backwards_motion: true   # 좁은 곳에서 재초기화 성공률↑
  
  # === feasibility 체크(디버그/완화) ===
  # feasibility_check_no_poses: 5            # 처음 5포즈만 충돌검사
  # feasibility_check_lookahead_distance: 1.0

  # 좁은 통로에서 전역경로 따르기 강화(옵션)
  # via_points_ordered: true
  # global_plan_viapoint_sep: 0.5
